# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_beta_cpp <- function(b, m, l, grid, p, K, basis, normalization_values) {
    .Call(`_bliss_compute_beta_cpp`, b, m, l, grid, p, K, basis, normalization_values)
}

compute_beta_sample_cpp <- function(posterior_sample, K, grid, p, basis, normalization_values) {
    .Call(`_bliss_compute_beta_sample_cpp`, posterior_sample, K, grid, p, basis, normalization_values)
}

moving_average_cpp <- function(v, range) {
    .Call(`_bliss_moving_average_cpp`, v, range)
}

Bliss_Gibbs_Sampler_cpp <- function(Q, y, x, grids, iter, K, basis, g, lambda, V_tilde, l_values, l_values_length, probs_l, progress, tol) {
    .Call(`_bliss_Bliss_Gibbs_Sampler_cpp`, Q, y, x, grids, iter, K, basis, g, lambda, V_tilde, l_values, l_values_length, probs_l, progress, tol)
}

Bliss_Simulated_Annealing_cpp <- function(iter, beta_sample, grid, burnin, Temp, k_max, p_l, dm, dl, p, basis, normalization_values, progress, starting_point) {
    .Call(`_bliss_Bliss_Simulated_Annealing_cpp`, iter, beta_sample, grid, burnin, Temp, k_max, p_l, dm, dl, p, basis, normalization_values, progress, starting_point)
}

dposterior_cpp <- function(rposterior, y, N, K, potential_intervals, potential_intervals_dims, p_l, Q) {
    .Call(`_bliss_dposterior_cpp`, rposterior, y, N, K, potential_intervals, potential_intervals_dims, p_l, Q)
}

