# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ginv_cpp <- function(X, tol) {
    .Call(`_bliss_ginv_cpp`, X, tol)
}

sqrt_mat <- function(X) {
    .Call(`_bliss_sqrt_mat`, X)
}

mvrnormArma <- function(mu, VarCovar, sigma_sq) {
    .Call(`_bliss_mvrnormArma`, mu, VarCovar, sigma_sq)
}

integrate_trapeze <- function(x, y) {
    .Call(`_bliss_integrate_trapeze`, x, y)
}

uniform_cpp <- function(m, l, grid) {
    .Call(`_bliss_uniform_cpp`, m, l, grid)
}

uniform_cpp_unnormalized <- function(m, l, grid) {
    .Call(`_bliss_uniform_cpp_unnormalized`, m, l, grid)
}

triangular_cpp <- function(m, l, grid) {
    .Call(`_bliss_triangular_cpp`, m, l, grid)
}

triangular_cpp_unnormalized <- function(m, l, grid) {
    .Call(`_bliss_triangular_cpp_unnormalized`, m, l, grid)
}

gaussian_cpp <- function(m, l, grid) {
    .Call(`_bliss_gaussian_cpp`, m, l, grid)
}

gaussian_cpp_unnormalized <- function(m, l, grid) {
    .Call(`_bliss_gaussian_cpp_unnormalized`, m, l, grid)
}

Epanechnikov_cpp <- function(m, l, grid) {
    .Call(`_bliss_Epanechnikov_cpp`, m, l, grid)
}

Epanechnikov_cpp_unnormalized <- function(m, l, grid) {
    .Call(`_bliss_Epanechnikov_cpp_unnormalized`, m, l, grid)
}

beta_build_cpp <- function(beta_star, m, l, grid, p, K, basis, scale_ml) {
    .Call(`_bliss_beta_build_cpp`, beta_star, m, l, grid, p, K, basis, scale_ml)
}

compute_beta_functions_cpp <- function(trace, p, K, grid, basis, scale_ml) {
    .Call(`_bliss_compute_beta_functions_cpp`, trace, p, K, grid, basis, scale_ml)
}

potential_intervals <- function(X, grid, l_max, basis) {
    .Call(`_bliss_potential_intervals`, X, grid, l_max, basis)
}

potential_intervals_List <- function(X_list, grids, l_max_vec, basis_vec, q) {
    .Call(`_bliss_potential_intervals_List`, X_list, grids, l_max_vec, basis_vec, q)
}

moving_average_cpp <- function(v, range) {
    .Call(`_bliss_moving_average_cpp`, v, range)
}

all_intervals_extract <- function(all_intervals, mk, lk, dims) {
    .Call(`_bliss_all_intervals_extract`, all_intervals, mk, lk, dims)
}

mk_update2 <- function(count, k, Y, beta_tilde, sigma_sq, m_q, l_q, X_tilde, all_intervals_q, all_intervals_dims_q, m_alternative_q, W_inv, eta_tilde, phi_m_q, p_q, prior_beta) {
    .Call(`_bliss_mk_update2`, count, k, Y, beta_tilde, sigma_sq, m_q, l_q, X_tilde, all_intervals_q, all_intervals_dims_q, m_alternative_q, W_inv, eta_tilde, phi_m_q, p_q, prior_beta)
}

mk_update_List <- function(count, k, Y, beta_tilde, sigma_sq, m_q, l_q, X_tilde, all_intervals_q, all_intervals_dims_q, m_alternative_q, eta_tilde, phi_m_q, p_q, prior_beta, Q, K, g, sum_K, lambda_id0) {
    .Call(`_bliss_mk_update_List`, count, k, Y, beta_tilde, sigma_sq, m_q, l_q, X_tilde, all_intervals_q, all_intervals_dims_q, m_alternative_q, eta_tilde, phi_m_q, p_q, prior_beta, Q, K, g, sum_K, lambda_id0)
}

lk_update_List <- function(count, k, Y, beta_tilde, sigma_sq, m_q, l_q, X_tilde, all_intervals_q, all_intervals_dims_q, l_alternative_q, eta_tilde, phi_l_q, lmax_q, prior_beta, Q, K, g, sum_K, lambda_id0) {
    .Call(`_bliss_lk_update_List`, count, k, Y, beta_tilde, sigma_sq, m_q, l_q, X_tilde, all_intervals_q, all_intervals_dims_q, l_alternative_q, eta_tilde, phi_l_q, lmax_q, prior_beta, Q, K, g, sum_K, lambda_id0)
}

beta_tilde_update <- function(Y, sigma_sq, eta_tilde, W_inv, X_tilde, Sigma_beta_tilde_inv, tol) {
    .Call(`_bliss_beta_tilde_update`, Y, sigma_sq, eta_tilde, W_inv, X_tilde, Sigma_beta_tilde_inv, tol)
}

loss_cpp <- function(d, grid, posterior_expe) {
    .Call(`_bliss_loss_cpp`, d, grid, posterior_expe)
}

Bliss_Gibbs_Sampler_multiple_cpp <- function(Q, Y, X, iter, grids, K, lmax, eta_tilde, a, b, probs_m, probs_l, prior_beta, g, lambda, V_tilde, tol, basis) {
    .Call(`_bliss_Bliss_Gibbs_Sampler_multiple_cpp`, Q, Y, X, iter, grids, K, lmax, eta_tilde, a, b, probs_m, probs_l, prior_beta, g, lambda, V_tilde, tol, basis)
}

Bliss_Simulated_Annealing_cpp <- function(iter, beta_functions, grid, burnin, Temp, k_max, l_max, dm, dl, p, basis, scale_ml) {
    .Call(`_bliss_Bliss_Simulated_Annealing_cpp`, iter, beta_functions, grid, burnin, Temp, k_max, l_max, dm, dl, p, basis, scale_ml)
}

dposterior_cpp <- function(rposterior, y, N, K, all_intervals, all_intervals_dims, lambda, l_max) {
    .Call(`_bliss_dposterior_cpp`, rposterior, y, N, K, all_intervals, all_intervals_dims, lambda, l_max)
}

